### PR TITLE
Update peerDependencies to support Grunt 1.0

### PR DESCRIPTION
**Pull request by grunt-updater2**
Update peerDependencies to support Grunt 1.0

Hello,

This is an automated issue request to update the `peerDependencies` for your Grunt plugin.
We ask you to merge this and **publish a new release on npm** to get your plugin working in Grunt 1.0!

Read more here: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies
Also on Twitter: https://twitter.com/gruntjs/status/700819604155707392

If you have any questions or you no longer have time to maintain this plugin, then please let us know in this thread.

Thanks for creating and working on this plugin!

(P.S. Close this PR if it is a mistake, sorry)

### CODE REVIEW

**Comment by steveoh** [comment]
Can you please merge this and cut a new release.

`npm ERR! peerinvalid Peer grunt-saucelabs@8.6.2 wants grunt@~0.4.1`

**Comment by XhmikosR** [comment]
@axemclion: ping

**Comment by XhmikosR** [comment]
@axemclion: ping ping

**Comment by axemclion** [comment]
@Jonahss has been helping maintain the repo. 
Hey @Jonahss - pinging on this issue ...

**Comment by XhmikosR** [comment]
Actually, this PR can be closed since https://github.com/axemclion/grunt-saucelabs/commit/2159acc63389db67b5a00b1eb625d519002498a2 is in. but we need a new version released ASAP.

**Comment by Jonahss** [comment]
Gotcha. I can do a release if that's what we need.

**Comment by XhmikosR** [comment]
@Jonahss: yes, please cut a new release and publish it on npm.

**Comment by Jonahss** [comment]
@XhmikosR I can do that, but it looks like tests aren't passing.
I haven't touched this repo in a long time and am now pretty lost. Gonna try to sort things out.

**Comment by XhmikosR** [comment]
@Jonahss: I don't see that here. https://travis-ci.org/axemclion/grunt-saucelabs/builds/110716193

**Comment by Jonahss** [comment]
Published 8.6.3

**Pull request closed without merging**
