### PR TITLE
updated saucelabs and lodash versions to fix security vulnerabilities

### PR DESCRIPTION
**Pull request by digitalfrost**
Updated lodash fixes: https://nodesecurity.io/advisories/577

Updated saucelabs fixes: https://nodesecurity.io/advisories/593   

According to npm audit these should be a non breaking changes

### CODE REVIEW

**Comment by admc** [comment]
Cool!

**Comment by Jonahss** [comment]
@digitalfrost you have publish permissions for this module, right?

Also, hi @admc !

**Comment by digitalfrost** [comment]
@Jonahss - no I do not have publish permissions for this module.

**Comment by Jonahss** [comment]
@digitalfrost Oh ok, I'll see what I can do.
Do you use grunt-saucelabs often?

**Comment by digitalfrost** [comment]
@Jonahss - not directly - this issue affects the popular [p5.js](https://p5js.org/) library as it uses grunt-saucelabs....

**Comment by mar10** [comment]
@axemclion or @Jonahss could you please merge this PR and release?

**Comment by Jonahss** [comment]
Thank you for the ping @mar10. I've just joined Jonathan Lipps as an Appium consultant at [Cloud Grey](https://cloudgrey.io/) so I'll be back in the testing industry! Will be able to be much more involved and responsive.

I was having trouble running the tests for this repository. I will merge your changes and publish now, but double check to make sure that everything works for you.

**Comment by Jonahss** [comment]
published as v9.0.1

**Comment by mar10** [comment]
@Jonahss that was fast, thank you very much! Good to hear this cool tool gets some attention again.
Btw. I was just pinging. Kudos for the patch go to @digitalfrost ;-)

**Comment by mar10** [comment]
btw. `npm audit fix` now fixed the high-classified warning and some.
There is still a low and a medium one, that might get fixed by bumping `requestretry` to the latest version 3.1.0, but this would be a potentially breaking change since it increments the major version?

**Comment by Jonahss** [comment]
well if you can read the changes made in the newer version, maybe we could easily switch to it?

**Pull request merged**
