### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by evilaliv3**
@axemclion / @Jonahss : i took care of updating few dependencies that changed in the meantime;

could you tag a 0.8.3 in order to benefit of the the libraries i updated so far?

This pull request include also a simple revision in relation to the strict mode were a function was used before its' definition.

### CODE REVIEW

**Comment by evilaliv3** [comment]
the build seems to fail but it's due to the travis cache :/ it seems that the package update is not working that well in travis in relation to the dependencies of the updated dependencies.

anyway @axemclion you can simply go on travis and trash the npm cache and the build will work fine

\cc @travis-ci

**Comment by evilaliv3** [comment]
@BanzaiMan how you generally deal with build failure due to cache issues like here?

**Comment by BanzaiMan** [comment]
Admin user of the repository can delete the cache and rerun the build.

I'm curious, though, why you think this is a cache issue. Builds have been failing since April 27 last year. https://travis-ci.org/axemclion/grunt-saucelabs/builds/60280455

**Comment by evilaliv3** [comment]
@Banzai i'm not talking with reference with the official repositoy but with the current error that i had yesterday on my laptop due to a change of a version of the package where the only way to fix was to do an rm node_modules and a new npm install -d

**Comment by BanzaiMan** [comment]
@evilaliv3 How would I know why your build breaks on your machine? I'm really sorry, but I can't help you.

**Comment by evilaliv3** [comment]
sorry @BanzaiMan i was thinking to have been clear for the issue but you are right i was not mentioning all the details.

here anyhow is the question; 

sometimes in node projects happens the following:
- suppose one is using an npm cache
- suppose one is changing a version of a $package_name from VERSION_X to VERSION_Y inside package.json that includes others packages
- suppose doing npm install -d given this only change goes in error cause of bad packages that probably where not handling correctly dependency definitions and the only possibility for fixing it all is to do an ```rm -r node_modules && npm install -d```

this is what happened in this build https://travis-ci.org/axemclion/grunt-saucelabs/builds/102990317 where the issue you see is caused by the fact that the npm install -d is not reinstalling correctly the lodash package resulting in a bad environment.

it's clearly not a fault of travis as the bug is in pad packages (https://github.com/jscs-dev/node-jscs/issues/1730), but was simply asking if you know good recipes to avoid manually empy the cache

**Comment by axemclion** [comment]
I cleared the cache, and looks like the build seems to work now.

**Comment by evilaliv3** [comment]
Time for a merge and for a release @axemclion !

**Comment by axemclion** [comment]
Just merged, but the tests are failing ...

**Comment by evilaliv3** [comment]
let me recheck

**Comment by evilaliv3** [comment]
@axemclion would you please try to restart the build to see if that was simply caused by a network failure?

**Comment by evilaliv3** [comment]
anyway @axemclion it seems that in general you are not running all the tests on the pull-requests builds: https://travis-ci.org/axemclion/grunt-saucelabs/jobs/102990318

here the success you were considering is before launching saucelabs that probably is not launched.

**Comment by evilaliv3** [comment]
@axemclion do you have any update on this?

**Pull request merged**
